apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cusw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cusw
    app.kubernetes.io/part-of: tkwch-fix-0075-0054-app
  name: devfile-sample-cusw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cusw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cusw
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0054-tenant/tkwch-fix-0075-0054-app/devfile-sample-cusw@sha256:7948ded399df4f4a53392acdef5cc1a81bf9d0455aaade7e266449a09f2d0bc4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
